ENV: local
HTTPADDR: 8080
RPCADDR: 40010
HOST: 127.0.0.1

REDIS: 115.29.150.148:6379
jwt_key: user_signing_key

#数据库
DB:
  MYSQL:
    imdb:
      username: root
      password: geeRan1001
      path: 115.29.150.148:3306
      db_name: im
      config: charset=utf8&parseTime=True&loc=Local
      max-idle-conns: 10
      max-open-conns: 10
      log_mode: true